### ISSUE TITLE
TFIDF part

### ISSUE THREAD

**Issue by chiahuiliu** [chiahuiliu/claim_checking_Fall2018#1]
line 89, in process
    simTfidf = np.asarray(map(cosine_sim, xHeadlineTfidf, xBodyTfidf))[:, np.newaxis]
IndexError: too many indices for array

(shown in TFIDF feature file)

**Comment by MMarkZhang** [comment]
https://stackoverflow.com/questions/47733704/numpy-array-indexerror-too-many-indices-for-array

https://stackoverflow.com/questions/14793585/indexerror-too-many-indices
